import PROPTYPES from '../_utils/types'

export const selectPropTypes = {
  defaultActiveFirstOption: PROPTYPES.bool,
  multiple: PROPTYPES.bool,
  filterOption: PROPTYPES.any,
  // children: PROPTYPES.any,
  showSearch: PROPTYPES.bool,
  disabled: PROPTYPES.bool,
  allowClear: PROPTYPES.bool,
  showArrow: PROPTYPES.bool,
  tags: PROPTYPES.bool,
  prefixCls: PROPTYPES.string,
  // className: PROPTYPES.string,
  transitionName: PROPTYPES.string,
  optionLabelProp: PROPTYPES.string,
  optionFilterProp: PROPTYPES.string,
  animation: PROPTYPES.string,
  choiceTransitionName: PROPTYPES.string,
  // onChange: PROPTYPES.func,
  // onBlur: PROPTYPES.func,
  // onFocus: PROPTYPES.func,
  // onSelect: PROPTYPES.func,
  // onSearch: PROPTYPES.func,
  // onPopupScroll: PROPTYPES.func,
  // onMouseEnter: PROPTYPES.func,
  // onMouseLeave: PROPTYPES.func,
  // onInputKeyDown: PROPTYPES.func,
  placeholder: PROPTYPES.any,
  // onDeselect: PROPTYPES.func,
  labelInValue: PROPTYPES.bool,
  value: PROPTYPES.any,
  defaultValue: PROPTYPES.any,
  dropdownStyle: PROPTYPES.object,
  dropdownClassName: PROPTYPES.string,
  maxTagTextLength: PROPTYPES.number,
  maxTagCount: PROPTYPES.number,
  maxTagPlaceholder: PROPTYPES.any,
  tokenSeparators: PROPTYPES.arrayOf(PROPTYPES.string),
  getInputElement: PROPTYPES.func,
  showAction: PROPTYPES.arrayOf(PROPTYPES.string),
  autoFocus: PROPTYPES.bool,
  getPopupContainer: PROPTYPES.func,
}